// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/contact-us.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/page.ts";
import * as $4 from "./routes/api/seo.ts";
import * as $5 from "./routes/contact-us.tsx";
import * as $6 from "./routes/editMode.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/login.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/contact-us.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/page.ts": $3,
    "./routes/api/seo.ts": $4,
    "./routes/contact-us.tsx": $5,
    "./routes/editMode.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/login.tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
